**1. Файл minutes_n_ingredients.csv содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива numpy типа int32, используя np.loadtxt. Выведите на экран первые 5 строк массива.**

In [ ]:
import numpy as np
doc=np.loadtxt('minutes_n_ingredients.csv', delimiter=',',skiprows=1, dtype=np.int32)
print(doc[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


**2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.**

In [ ]:
import numpy as np
doc=np.loadtxt('minutes_n_ingredients.csv', delimiter=',',skiprows=1, dtype=np.int32)
doc1 = doc[:,1:]
print('cред. знач:', np.mean(doc1, axis=0) ,'min:', np.min(doc1, axis=0), 'max:', np.max(doc1, axis=0), 'медиана:',np.median(doc1, axis=0) )

cред. знач: [2.16010017e+04 9.05528000e+00] min: [0 1] max: [2147483647         39] медиана: [40.  9.]


**3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля q 0.75**

In [ ]:
print(doc[doc[:, 1] < np.quantile(doc[:, 1], 0.75)])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]


**4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.**

In [ ]:
print(len(doc[doc[:, 1] == 0]))
doc[doc[:, 1] == 0] = 1 #ответ 0, так как код уже прогнала и все значения заменились. первоначальный ответ=479

0


**5. Посчитайте, сколько уникальных рецептов находится в датасете.**

In [ ]:
print(len(np.unique(doc[:, 0])))

99285


**6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?**

In [ ]:
print(len(np.unique(doc[:, 2])))
print(*np.unique(doc[:, 2]))

37
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 37 39


**7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.**

In [ ]:
print(doc[doc[:, 2] <= 5])


[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


**8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета**

In [ ]:
print(doc[:, 2]/doc[:, 1]) 
print('максимальное:', np.max(doc[:, 2]/doc[:, 1]))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
максимальное: 14.0


**9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью**

In [ ]:
doc2 = doc[doc[:, 1].argsort()]
doc2 = doc2[-100:]
np.mean(doc2[:, 2])

6.61

**10. Выберите случайным образом и выведите информацию о 10 различных рецептах**

In [ ]:
doc[np.random.randint(np.size(doc, axis = 0), size=10)]

array([[148113,     55,     17],
       [106641,     50,      6],
       [413415,     10,     11],
       [104976,  28810,      6],
       [421802,     10,      9],
       [233474,     25,     11],
       [243654,      5,      4],
       [190815,     80,     10],
       [197762,     50,     12],
       [411869,      5,      3]], dtype=int32)

**11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.**

In [ ]:
srzn = np.mean(doc[:, 2])
klvo = len(doc[doc[:, 2] < srzn])
pros = (klvo / len(doc)) * 100
print(pros, '%')

58.998 %


**12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.**

In [ ]:
print(np.c_[doc, (doc[:, 1] <= 20) & (doc[:, 2] <= 5)])

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


**13. Выведите процент "простых" рецептов в датасете**

In [ ]:
doc4=np.c_[doc, (doc[:, 1] <= 20) & (doc[:, 2] <= 5)]
print((len(doc4[doc4[:, 3] == 1])/len(doc4))*100)

9.991999999999999


**14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.**

In [ ]:
print('к величайшему сожалению, тут я бессильна')

к величайшему сожалению, тут я бессильна
